package com.landray.kmss.km.review.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2017-06-28T14:53:33.532+08:00
 * Generated source version: 3.1.6
 * 
 */
@WebServiceClient(name = "IKmReviewQueryDataWebserviceServiceService", 
                  wsdlLocation = "file:/Users/hyy/liucheng.xml",
                  targetNamespace = "http://webservice.review.km.kmss.landray.com/") 
public class IKmReviewQueryDataWebserviceServiceService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://webservice.review.km.kmss.landray.com/", "IKmReviewQueryDataWebserviceServiceService");
    public final static QName IKmReviewQueryDataWebserviceServicePort = new QName("http://webservice.review.km.kmss.landray.com/", "IKmReviewQueryDataWebserviceServicePort");
    static {
        URL url = null;
        try {
            url = new URL("file:/Users/hyy/liucheng.xml");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(IKmReviewQueryDataWebserviceServiceService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/Users/hyy/liucheng.xml");
        }
        WSDL_LOCATION = url;
    }

    public IKmReviewQueryDataWebserviceServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public IKmReviewQueryDataWebserviceServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IKmReviewQueryDataWebserviceServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public IKmReviewQueryDataWebserviceServiceService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public IKmReviewQueryDataWebserviceServiceService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public IKmReviewQueryDataWebserviceServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns IKmReviewQueryDataWebserviceService
     */
    @WebEndpoint(name = "IKmReviewQueryDataWebserviceServicePort")
    public IKmReviewQueryDataWebserviceService getIKmReviewQueryDataWebserviceServicePort() {
        return super.getPort(IKmReviewQueryDataWebserviceServicePort, IKmReviewQueryDataWebserviceService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IKmReviewQueryDataWebserviceService
     */
    @WebEndpoint(name = "IKmReviewQueryDataWebserviceServicePort")
    public IKmReviewQueryDataWebserviceService getIKmReviewQueryDataWebserviceServicePort(WebServiceFeature... features) {
        return super.getPort(IKmReviewQueryDataWebserviceServicePort, IKmReviewQueryDataWebserviceService.class, features);
    }

}
