
package com.landray.kmss.km.review.webservice;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2017-06-28T14:53:33.529+08:00
 * Generated source version: 3.1.6
 * 
 */
 
public class IKmReviewQueryDataWebserviceService_IKmReviewQueryDataWebserviceServicePort_Server{

    protected IKmReviewQueryDataWebserviceService_IKmReviewQueryDataWebserviceServicePort_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new IKmReviewQueryDataWebserviceServicePortImpl();
        String address = "http://ems.evergrande.com/ekp/sys/webservice/kmReviewQueryDataWebservice";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws java.lang.Exception { 
        new IKmReviewQueryDataWebserviceService_IKmReviewQueryDataWebserviceServicePort_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
