
package com.landray.kmss.km.review.webservice;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.Map;

import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.BindingProvider;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.6 2017-06-28T14:53:33.502+08:00
 * Generated source version: 3.1.6
 * 
 */
public final class IKmReviewQueryDataWebserviceService_IKmReviewQueryDataWebserviceServicePort_Client {

	private static final QName SERVICE_NAME = new QName("http://webservice.review.km.kmss.landray.com/", "IKmReviewQueryDataWebserviceServiceService");

	private IKmReviewQueryDataWebserviceService_IKmReviewQueryDataWebserviceServicePort_Client() {
	}

	public static void main(String args[]) throws java.lang.Exception {
		URL wsdlURL = IKmReviewQueryDataWebserviceServiceService.WSDL_LOCATION;
		if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
			File wsdlFile = new File(args[0]);
			try {
				if (wsdlFile.exists()) {
					wsdlURL = wsdlFile.toURI().toURL();
				} else {
					wsdlURL = new URL(args[0]);
				}
			} catch (MalformedURLException e) {
				e.printStackTrace();
			}
		}

		IKmReviewQueryDataWebserviceServiceService ss = new IKmReviewQueryDataWebserviceServiceService(wsdlURL, SERVICE_NAME);
		IKmReviewQueryDataWebserviceService port = ss.getIKmReviewQueryDataWebserviceServicePort();
		BindingProvider bp = (BindingProvider) port;
		Map<String, Object> context = bp.getRequestContext();
		context.put(BindingProvider.USERNAME_PROPERTY, "hlwjr");
		context.put(BindingProvider.PASSWORD_PROPERTY, "daf96bf47d41df6b18eb84679a4d4e5b");
		System.out.println(bp.getRequestContext());
//		context.put(BindingProvider.USERNAME_PROPERTY, "guestsys");
//		context.put(BindingProvider.PASSWORD_PROPERTY, "f5759bd0e77c15055711750ce4122536");
//		context.put("tns:user", "guestsys");
//		context.put("tns:password", "f5759bd0e77c15055711750ce4122536");

		System.out.println("Invoking getProcessInfos...");
		String templateIds = "152161d63099c73e54d6ff948bca717d";
		String modelIds = null;// "1593ef2dae124ee27325f2e4106ac426";
		// String params = "{'rowSize':1000, 'pageNo':1, 'status':'10;11;30'}";
		String params = null;// "{'rowSize':1000, 'pageNo':1, 'status':'20'}";
		try {
			String s = port.getProcessInfos(templateIds, modelIds, params);
			System.out.println("getProcessInfos.result=" + s);
		} catch (Exception_Exception e) {
			e.printStackTrace();
		}
		System.exit(0);
	}

}
