
package com.landray.kmss.km.review.webservice.flowinfo;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2017-06-29T15:20:19.719+08:00
 * Generated source version: 3.1.6
 * 
 */
 
public class IKmReviewGetMainDataService_IKmReviewGetMainDataServicePort_Server{

    protected IKmReviewGetMainDataService_IKmReviewGetMainDataServicePort_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new IKmReviewGetMainDataServicePortImpl();
        String address = "http://ems.evergrande.com/ekp/sys/webservice/kmReviewGetMainDataService";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws java.lang.Exception { 
        new IKmReviewGetMainDataService_IKmReviewGetMainDataServicePort_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
