package com.landray.kmss.km.review.webservice.flowinfo;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2017-06-30T16:03:09.536+08:00
 * Generated source version: 2.4.2
 * 
 */
@WebServiceClient(name = "IKmReviewGetMainDataServiceService", 
                  wsdlLocation = "http://192.168.99.6:9081/ekp/sys/webservice/kmReviewGetMainDataService?wsdl",
                  targetNamespace = "http://flowinfo.webservice.review.km.kmss.landray.com/") 
public class IKmReviewGetMainDataServiceService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://flowinfo.webservice.review.km.kmss.landray.com/", "IKmReviewGetMainDataServiceService");
    public final static QName IKmReviewGetMainDataServicePort = new QName("http://flowinfo.webservice.review.km.kmss.landray.com/", "IKmReviewGetMainDataServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://192.168.99.6:9081/ekp/sys/webservice/kmReviewGetMainDataService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(IKmReviewGetMainDataServiceService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://192.168.99.6:9081/ekp/sys/webservice/kmReviewGetMainDataService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public IKmReviewGetMainDataServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public IKmReviewGetMainDataServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IKmReviewGetMainDataServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public IKmReviewGetMainDataServiceService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public IKmReviewGetMainDataServiceService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public IKmReviewGetMainDataServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns IKmReviewGetMainDataService
     */
    @WebEndpoint(name = "IKmReviewGetMainDataServicePort")
    public IKmReviewGetMainDataService getIKmReviewGetMainDataServicePort() {
        return super.getPort(IKmReviewGetMainDataServicePort, IKmReviewGetMainDataService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IKmReviewGetMainDataService
     */
    @WebEndpoint(name = "IKmReviewGetMainDataServicePort")
    public IKmReviewGetMainDataService getIKmReviewGetMainDataServicePort(WebServiceFeature... features) {
        return super.getPort(IKmReviewGetMainDataServicePort, IKmReviewGetMainDataService.class, features);
    }

}
