
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.landray.kmss.km.review.webservice.flowinfo;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2017-06-29T15:20:19.709+08:00
 * Generated source version: 3.1.6
 * 
 */

@javax.jws.WebService(
                      serviceName = "IKmReviewGetMainDataServiceService",
                      portName = "IKmReviewGetMainDataServicePort",
                      targetNamespace = "http://flowinfo.webservice.review.km.kmss.landray.com/",
                      wsdlLocation = "file:/Users/hyy/liucheng2.xml",
                      endpointInterface = "com.landray.kmss.km.review.webservice.flowinfo.IKmReviewGetMainDataService")
                      
public class IKmReviewGetMainDataServicePortImpl implements IKmReviewGetMainDataService {

    private static final Logger LOG = Logger.getLogger(IKmReviewGetMainDataServicePortImpl.class.getName());

    /* (non-Javadoc)
     * @see com.landray.kmss.km.review.webservice.flowinfo.IKmReviewGetMainDataService#getKmReviewMainData(java.lang.String  arg0 ,)java.lang.String  arg1 ,)java.lang.String  arg2 ,)java.lang.String  arg3 ,)java.lang.String  arg4 ,)java.lang.String  arg5 ,)java.lang.String  arg6 )*
     */
    public java.lang.String getKmReviewMainData(java.lang.String arg0,java.lang.String arg1,java.lang.String arg2,java.lang.String arg3,java.lang.String arg4,java.lang.String arg5,java.lang.String arg6) throws Exception_Exception    { 
        LOG.info("Executing operation getKmReviewMainData");
        System.out.println(arg0);
        System.out.println(arg1);
        System.out.println(arg2);
        System.out.println(arg3);
        System.out.println(arg4);
        System.out.println(arg5);
        System.out.println(arg6);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new Exception_Exception("Exception...");
    }

}
